services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: minibo
      POSTGRES_PASSWORD: minibo
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: minibo
    hostname: minibo
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: minibo@example.com
      PGADMIN_DEFAULT_PASSWORD: minibo
    depends_on:
      - db
